Выполнено задание к уроку 2
GSergeevich/test-guru pull request #1
Opened 2021-02-27 12:05 UTC by GSergeevich

Выполнено задание 2

2021-02-28 13:53 UTC, VidgarVii requested changes

2021-02-28 13:53 UTC, VidgarVii commented on config/initializers/version.rb
> +APP_VERSION = '0.1.0'
1  В Ruby константы можно переопределять. По этому чтобы защитить данные, их надо фризить. Заморозка так же благоприятно сказывается на производительности ПО. 
2 не стоит засорять глобальное пространство
версия относится к приложению, так что и константу нужно объявить в его контексте

посмотри к примеру в файл `config/application.rb` в какой модуль обернуто все твое приложение (9-я строка)

```ruby
module TestGuru
  VERSION = '0.1.0'.freeze
end
```
или

```ruby
module TestGuru
  class Application < Rails::Application
    VERSION = '0.1.0'.freeze
  end
end
```

2021-02-28 13:53 UTC, VidgarVii commented on app/controllers/about_controller.rb
> +end
4 Добавьте **статическую** страницу /about

Т.е. надо просто создать html файл в папке public
файлы из `public` отдаются минуя контроллеры "как есть", т.е. без лэйаута
это означает, что здесь должен быть полноценная `html` страница, которая открывается тегом `<!DOCTYPE html>` и содержит теги `<html>`, `<head>`, `<body>` и т.д.

2021-02-28 13:53 UTC, VidgarVii commented on app/controllers/version_controller.rb
> +end
нет такого задания сделать страницу, в которой надо показывать версию ПО

2021-02-28 13:53 UTC, VidgarVii commented on app/views/about/author.html
> +      <a href="https://github.com/GSergeevich">
ссылки на сторонние ресурсы правильно открывать в новом окне

2021-02-28 13:53 UTC, VidgarVii commented on app/views/about/about.html
> +<ul>Создаётся в рамках учебного курса www.thinknetica.com</ul>
www.thinknetica.com должна быть кликабельная ссылка

2021-02-28 13:53 UTC, VidgarVii commented on README.md
> +Тесты
как-то мало получилось сущностей )))

список сущностей приложения обычно выводится из сценария использования приложения

сценарий использования приложения примерно такой:
- Пользователь заходит на сайт
- он выбирает Тест
- Тест может принадлежать к одной из Категорий
- Тест состоит из Вопросов
- на каждый Вопрос есть несколько Ответов
- Пользователь выбирает один или несколько Ответов, чтобы ответить на каждый из Вопросов
- Результат тестирования сохраняется

2021-02-28 15:03 UTC, GSergeevich commented on app/controllers/version_controller.rb
> +end
Если инициатива не приветствуется - удалю)

2021-02-28 15:33 UTC, GSergeevich commented on app/controllers/about_controller.rb
> +end
Не нашёл как сделать статичную страницу с именем включающем слэш, и отдающуюся без роута из подзадания 5:
_Добавьте статическую страницу /about/author с информацией об авторе (включая ссылку на GitHub профиль)_ 
потому сделал обе статические страницы одинаково.Исправил для 4 подзадания.

2021-03-01 06:40 UTC, VidgarVii requested changes

2021-03-01 06:40 UTC, VidgarVii commented on app/controllers/about_controller.rb
> +end
просто в директории public создаёшь папку about и в ней создаёшь файл author.html
а для странице о проекте. Так же в папке about создаешь страницу index.html. И она будет открываться по запросу /about

2021-03-01 06:40 UTC, VidgarVii commented on config/application.rb
> +    APP_VERSION = '0.1.0'.freeze
согласно ДЗ версия ПО должна быть указана в initializer

2021-03-01 07:03 UTC, GSergeevich commented on config/application.rb
> +    APP_VERSION = '0.1.0'.freeze
В предыдущий раз я сделал в initializer, но мне было рекомендовано перенести в объявление модуля.Или я что-то не так понял?
![image](https://user-images.githubusercontent.com/19465989/109462933-43ab6380-7a75-11eb-8d53-3b4257387663.png)

2021-03-01 13:19 UTC, VidgarVii commented on app/views/version/show.html.erb
> +<p><%= APP_VERSION %></p>
этот файл можно удалить

2021-03-01 13:19 UTC, VidgarVii commented on config/initializers/version.rb
> +  APP_VERSION = '0.1.0'.freeze
обычно пишут просто VERSION
еще не помешало бы обернуть в класс Application

2021-03-23 11:21 UTC, merged