Добавлены модели и миграции
GSergeevich/test-guru pull request #2
Opened 2021-03-28 19:54 UTC by GSergeevich

2021-03-30 10:23 UTC, VidgarVii commented on app/models/answer.rb
> +  belongs_to :question
в этом ДЗ мы еще не определяем связи. Ассоциации будут далее по уроку

2021-03-30 10:32 UTC, VidgarVii requested changes

2021-03-30 10:32 UTC, VidgarVii commented on db/migrate/20210327203000_create_tests.rb
> +      t.integer :level , :default => 0
так же не хватает null: false

2021-03-30 10:32 UTC, VidgarVii commented on db/migrate/20210327203000_create_tests.rb
> +      t.string :title , null: false
лишний пробел

2021-03-30 10:32 UTC, VidgarVii commented on db/migrate/20210327210453_create_answers.rb
> +      t.boolean :correct , :default => false
default: false

2021-03-30 10:32 UTC, VidgarVii commented on db/migrate/20210327210453_create_answers.rb
> +      t.text :body , null: false
перед запятой пробел не нужен

2021-03-30 10:32 UTC, VidgarVii commented on db/migrate/20210327204102_create_questions.rb
> +      t.text :body , null: false
тип text в данном кейсе оверхед. Мы не будем использовать столько памяти. Нам достаточно везде проставить string

2021-03-30 10:32 UTC, VidgarVii commented on db/migrate/20210330081351_create_users.rb
> +      t.boolean :admin, :default => false
Админ это роль/тип/профессия пользователя. Их мб много. Это надо закладывать на уровне проектирования. Т.е. в самом начале. 
Мы будем реализовывать администратора системы паттерном STI. 
Так что данное поле лучше удалить

2021-03-30 10:33 UTC, VidgarVii requested changes

2021-03-30 10:33 UTC, VidgarVii commented on db/migrate/20210327203000_create_tests.rb
> +    end
У теста так же должна быть связь с автором

2021-03-30 11:03 UTC, GSergeevich commented on app/models/answer.rb
> +  belongs_to :question
В этом есть что-то неправильное,кроме того что я сделал это не вовремя?

2021-04-01 05:16 UTC, VidgarVii requested changes

2021-04-01 05:16 UTC, VidgarVii commented on db/migrate/20210327203000_create_tests.rb
> +      t.references :user, null: false, foreign_key: true
лучше обозвать поле автор. Так сразу будет понятно за что отвечает связь.
Чтобы работало надо будет указать опию `to_table`

2021-04-01 05:16 UTC, VidgarVii commented on app/models/answer.rb
> +  belongs_to :question
лучше удалить. В мастер ветке должен находиться законченная реализация фич. А сейчас у тебя ассоциации не полноценные и объявлены не все

2021-04-02 06:35 UTC, GSergeevich commented on app/models/answer.rb
> +  belongs_to :question
Понял,спасибо.

2021-04-02 07:04 UTC, merged